# Generated by Django 5.1.4 on 2024-12-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questions_text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='quizsession',
            old_name='incoorrect_answer',
            new_name='correct_answers',
        ),
        migrations.RenameField(
            model_name='quizsession',
            old_name='correct_answer',
            new_name='incorrect_answers',
        ),
        migrations.RenameField(
            model_name='quizsession',
            old_name='total_quetion',
            new_name='total_questions',
        ),
    ]
